### ISSUE TITLE
Choose new name 

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/geo-commandline-bootcamp#15]
from @auremoser (just wanted to move these nice ideas into the repo):

I all! Such great news, I'm sorry I'm so late to this.
## Some resources:
- Mike Bostock has a nice little overview of some gdal/ogr in the wild in this tutorial: https://bost.ocks.org/mike/map/. 
- Derrick Watkins has a sweet little cheat sheet of basic operations here: https://github.com/dwtkns/gdal-cheat-sheet
- There's even a readthedocs version here: http://headfirst-gdal.readthedocs.io/en/latest/gdal-cheat-sheet.html
- For more Postgres and ogr stuff, here's a good one: http://skipperkongen.dk/tricks/ogr2ogr-tricks/
- Shortcuts has a nice little edu gui for learning: https://www.shortcutfoo.com/app/dojos/command-line
## Some names:
- prof-cli = o.k. I think "Professor Command-Line" tutorial series would be very cute, and you could do the geo/general/etc. editions other editions: prof-geo, prof-sed...
- cle = command line education (I checked, there are no offensive acronyms that use these same letters; clé is also "key" in french, for what it's worth)
- cli-foo = simple easy, works with all topics. 
- you could go the geo-foo route for sub-naming, or edu-foo which has the rhyming benefit
- I would also suggest animating the name in your readme with ascii gen. In fact, I am happy to do this when you choose a name.

**Comment by auremoser** [comment]
Hello all! 
I like `prof-cli-geo` + `prof-cli`. I'm not sure I can re-name this repo because I don't have admin rights to the settings (totes fine), but if you're cool with that name, I vote for that. If there's a way for me to clone and change, I'm happy to do that but I do think it has to happen in Settings.

**Comment by joeyklee** [comment]
Super. Then let's start the `prof-cli` series with `prof-cli-geo`! woo hoo! go team!
